/**
 * Bile Browser Configuration
 * Browser-specific constants for userscript environment
 */

const BileBrowserConfig = {
    // Common UI Selectors for article detection
    UI_SELECTORS: {
        ARTICLE_CONTAINERS: [
            'article',
            '[role="article"]',
            '.article-content',
            '.article-body',
            '.post-content',
            '.entry-content',
            '.content',
            'main',
            '.story-body',
            '.article-text',
            '.content-body'
        ],

        TITLE_SELECTORS: [
            'h1',
            '.article-title',
            '.post-title',
            '.entry-title',
            '.headline',
            'header h1',
            '.title'
        ],

        PARAGRAPH_SELECTORS: [
            'p',
            '.article p',
            '.post-content p',
            '.entry-content p',
            '.content p'
        ]
    },

    // Browser-specific UI settings
    UI_SETTINGS: {
        BUTTON_POSITION_DEFAULT: 'top-right',
        MODAL_Z_INDEX: '2147483647',
        ANIMATION_DURATION: 300
    },

    // File header template for generated files
    GENERATED_FILE_HEADER: ` * This file is automatically generated. Do not edit directly.
 * Source files are in the src/ directory.`,

    // Create combined config for browser environment
    createBrowserConstants(coreConfig) {
        return {
            ...coreConfig,
            ...this,
            // Keep the old structure for backward compatibility
            UI_SELECTORS: this.UI_SELECTORS,
            CONFIG: {
                ...coreConfig.PROCESSING,
                ...this.UI_SETTINGS
            }
        };
    },

    // Include the constants file in the built userscript
    generateConstantsInclude(coreConfig) {
        const combinedConfig = this.createBrowserConstants(coreConfig);
        return `
// Shared constants
window.BileConstants = ${JSON.stringify(combinedConfig, null, 4)};
`;
    }
};

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = BileBrowserConfig;
} else if (typeof window !== 'undefined') {
    window.BileBrowserConfig = BileBrowserConfig;
}