/**
 * Bile Shared Constants
 * Centralized location for commonly used constants to avoid duplication
 */

const BileConstants = {
    // OpenRouter free models (referenced from model-config.js)
    FREE_MODELS: [
        'moonshotai/kimi-k2:free',
        'deepseek/deepseek-r1-0528:free',
        'tngtech/deepseek-r1t2-chimera:free',
        'qwen/qwen3-235b-a22b:free',
        'microsoft/mai-ds-r1:free'
    ],

    // API Configuration
    API: {
        BASE_URL: 'https://openrouter.ai/api/v1/chat/completions',
        MAX_TOKENS: 4000,
        DEFAULT_TEMPERATURE: 0.3,
        TIMEOUT: 30000
    },

    // Common UI Selectors for article detection
    UI_SELECTORS: {
        ARTICLE_CONTAINERS: [
            'article',
            '[role="article"]',
            '.article-content',
            '.article-body',
            '.post-content',
            '.entry-content',
            '.content',
            'main',
            '.story-body',
            '.article-text',
            '.content-body'
        ],
        
        TITLE_SELECTORS: [
            'h1',
            '.article-title',
            '.post-title',
            '.entry-title',
            '.headline',
            'header h1',
            '.title'
        ],

        PARAGRAPH_SELECTORS: [
            'p',
            '.article p',
            '.post-content p',
            '.entry-content p',
            '.content p'
        ]
    },

    // Common JSON response templates
    RESPONSE_TEMPLATES: {
        BASIC_TRANSLATION_RESPONSE: `{
  "source_language": "detected_language_code",
  "target_language": "TARGET_LANG_PLACEHOLDER",
  "title_original": "original title",
  "title_translated": "translated title",
  "content": [
    {
      "type": "paragraph",
      "original": "original text with <slang>preserved terms</slang>",
      "translated": "translated text with <slang>preserved terms</slang> in context",
      "slang_terms": [
        {
          "term": "example",
          "translation": "example translation",
          "explanation": "Brief explanation for learners"
        }
      ]
    }
  ]
}`,
        
        TRANSLATION_RESPONSE: `{
  "translations": [
    {
      "original": "source text here",
      "segments": [
        {
          "term": "example",
          "translation": "example translation",
          "explanation": "Brief explanation for learners"
        }
      ]
    }
  ]
}`,

        ENHANCED_TRANSLATION_RESPONSE: `{
  "source_language": "detected_language_code",
  "target_language": "TARGET_LANG_PLACEHOLDER",
  "title_original": "original article title",
  "title_translated": "translated article title",
  "content": [
    {
      "type": "paragraph",
      "original": "original text with cultural terms preserved",
      "translated": "high-quality translation preserving tone and meaning",
      "slang_terms": [
        {
          "term": "cultural_term_or_slang",
          "translation": "English_equivalent",
          "explanation_original": "detailed explanation in source language",
          "explanation_translated": "detailed explanation in target language"
        }
      ]
    }
  ]
}`
    },

    // Error handling patterns
    ERROR_HANDLERS: {
        LOG_AND_THROW: (context, error) => {
            if (console && console.error) {
                console.error(`${context} failed:`, error);
            }
            throw error;
        },

        LOG_WITH_CONTEXT: (context, details) => {
            if (console && console.error) {
                console.error(context, details);
            }
        }
    },

    // File header template for generated files (just text, no comment syntax)
    GENERATED_FILE_HEADER: ` * This file is automatically generated. Do not edit directly.
 * Source files are in the src/ directory.`,

    // Include the constants file in the built userscript
    generateConstantsInclude() {
        return `
// Shared constants
window.BileConstants = ${JSON.stringify(this, null, 4)};
`;
    }
};

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = BileConstants;
} else if (typeof window !== 'undefined') {
    window.BileConstants = BileConstants;
}